# syntax=docker/dockerfile:1

FROM node:20-bookworm-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-bookworm-slim AS production

WORKDIR /app

ENV PLAYWRIGHT_BROWSERS_PATH=/app/.cache/ms-playwright

COPY package*.json ./
RUN npm ci --omit=dev && \
    npx -y playwright@1.57.0 install --with-deps chromium

COPY --from=builder /app/dist ./dist

RUN chown -R node:node /app
USER node

EXPOSE 3000

CMD ["node", "dist/src/main.js"]
